from django.core.exceptions import ValidationError
from django.db import IntegrityError, transaction
from django.test import TestCase

from apps.catalog.models import Product


def make_merchandise(**overrides):
    defaults = dict(
        sku="plant-1",
        name="Ficus",
        item_type=Product.ItemType.MERCHANDISE,
        species="Ficus lyrata",
        latin_name="Ficus lyrata",
        genus="Ficus",
        variety="Lyrata",
        pot_size="12cm",
        low_stock_threshold=5,
    )
    defaults.update(overrides)
    return Product(**defaults)


def make_consumable(**overrides):
    defaults = dict(
        sku="box-1",
        name="Cardboard box",
        item_type=Product.ItemType.CONSUMABLE,
        length=10,
        width=10,
        height=10,
        dimension_unit=Product.DimensionUnit.CENTIMETERS,
        material_unit=Product.MaterialUnit.PIECES,
    )
    defaults.update(overrides)
    return Product(**defaults)


class ProductSkuTests(TestCase):
    def test_sku_is_normalized_trim_and_upper(self):
        product = make_merchandise(sku="  plant-1 ")
        product.full_clean()
        product.save()
        self.assertEqual(product.sku, "PLANT-1")

    def test_sku_uniqueness_after_normalization_raises_validation_error(self):
        make_merchandise(sku="PLANT-1").save()
        duplicate = make_merchandise(sku=" plant-1 ", name="Other")
        with self.assertRaises(ValidationError):
            duplicate.full_clean()

    def test_sku_uniqueness_enforced_at_db_level(self):
        make_merchandise(sku="PLANT-1").save()
        duplicate = make_merchandise(sku="PLANT-1", name="Other")
        with self.assertRaises(IntegrityError):
            with transaction.atomic():
                duplicate.save()


class ProductMerchandiseValidationTests(TestCase):
    def test_requires_plant_fields(self):
        product = make_merchandise(species="")
        with self.assertRaises(ValidationError) as ctx:
            product.full_clean()
        self.assertIn("species", ctx.exception.message_dict)

    def test_rejects_material_fields(self):
        product = make_merchandise(length=5)
        with self.assertRaises(ValidationError) as ctx:
            product.full_clean()
        self.assertIn("length", ctx.exception.message_dict)

    def test_low_stock_threshold_required(self):
        product = make_merchandise(low_stock_threshold=None)
        with self.assertRaises(ValidationError) as ctx:
            product.full_clean()
        self.assertIn("low_stock_threshold", ctx.exception.message_dict)


class ProductConsumableValidationTests(TestCase):
    def test_requires_positive_dimensions(self):
        for field in ("length", "width", "height"):
            product = make_consumable(**{field: 0})
            with self.assertRaises(ValidationError) as ctx:
                product.full_clean()
            self.assertIn(field, ctx.exception.message_dict)

    def test_requires_dimension_and_material_unit(self):
        product = make_consumable(dimension_unit="")
        with self.assertRaises(ValidationError) as ctx:
            product.full_clean()
        self.assertIn("dimension_unit", ctx.exception.message_dict)

    def test_rejects_plant_fields(self):
        product = make_consumable(species="Ficus")
        with self.assertRaises(ValidationError) as ctx:
            product.full_clean()
        self.assertIn("species", ctx.exception.message_dict)


class ProductSlugTests(TestCase):
    def test_slug_autogenerated_from_name_and_sku(self):
        product = make_merchandise(sku="PLANT-1", name="Ficus")
        product.full_clean()
        product.save()
        self.assertEqual(product.slug, "ficus-plant-1")

    def test_slug_collision_gets_suffix(self):
        # Force an existing row to occupy the slug that the next product's
        # name+sku would naturally generate, to exercise the suffixing loop.
        occupying = make_merchandise(sku="OTHER-1", name="Something else")
        occupying.slug = "ficus-plant-2"
        occupying.save()

        colliding = make_merchandise(sku="PLANT-2", name="Ficus", low_stock_threshold=1)
        colliding.full_clean()
        colliding.save()

        self.assertEqual(colliding.slug, "ficus-plant-2-2")


class ProductStrTests(TestCase):
    def test_str_representation(self):
        product = make_merchandise(sku="PLANT-1", name="Ficus")
        self.assertEqual(str(product), "PLANT-1 — Ficus")
