# Generated by Django 6.1 on 2026-09-01 14:14

import apps.common.crypto
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_alter_product_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('ALLEGRO', 'Allegro')], default='ALLEGRO', max_length=20)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Produkcja')], default='sandbox', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_email', models.EmailField(blank=True, max_length=254)),
                ('credentials', apps.common.crypto.EncryptedJSONField(blank=True, null=True)),
                ('last_event_id', models.CharField(blank=True, max_length=100)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('oauth_state', models.CharField(blank=True, max_length=64)),
                ('oauth_state_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Integracja marketplace',
                'verbose_name_plural': 'Integracje marketplace',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['type', 'is_active'], name='marketplace_type_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('picture_url', models.URLField(blank=True, max_length=500)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktywna'), ('ENDED', 'Zakończona')], default='ACTIVE', max_length=20)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='marketplaces.marketplace')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_listings', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Mapowanie oferty',
                'verbose_name_plural': 'Mapowania ofert',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['product'], name='marketplace_listing_prod_idx')],
                'constraints': [models.UniqueConstraint(fields=('marketplace', 'external_id'), name='marketplace_listing_unique_offer')],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('EVENTS', 'Import zamówień'), ('TOKEN_REFRESH', 'Odświeżenie tokenu')], max_length=20)),
                ('status', models.CharField(choices=[('OK', 'Zakończona'), ('PARTIAL', 'Częściowa'), ('FAILED', 'Błąd')], default='OK', max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('events_seen', models.PositiveIntegerField(default=0)),
                ('orders_imported', models.PositiveIntegerField(default=0)),
                ('orders_skipped', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='marketplaces.marketplace')),
            ],
            options={
                'verbose_name': 'Przebieg synchronizacji',
                'verbose_name_plural': 'Przebiegi synchronizacji',
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['marketplace', '-started_at'], name='marketplace_sync_run_idx')],
            },
        ),
    ]
