# Generated by Django 6.1 on 2026-09-04 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_shipping_cost_order_shipping_cost_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Otwarta'), ('DONE', 'Zakończona'), ('CANCELLED', 'Anulowana')], default='OPEN', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfillment_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fala realizacji',
                'verbose_name_plural': 'Fale realizacji',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FulfillmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_packed', models.BooleanField(default=False)),
                ('packed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.fulfillmentbatch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Zamówienie w fali',
                'verbose_name_plural': 'Zamówienia w fali',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='fulfillmentbatch',
            index=models.Index(fields=['status'], name='logistics_batch_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='fulfillmentorder',
            constraint=models.UniqueConstraint(fields=('batch', 'order'), name='logistics_batch_order_unique'),
        ),
    ]
