# Generated by Django 6.1 on 2026-09-01 14:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_alter_product_item_type'),
        ('marketplaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_order_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('NEW', 'Nowe'), ('IN_FULFILLMENT', 'W realizacji'), ('SHIPPED', 'Wysłane'), ('CANCELLED', 'Anulowane')], default='NEW', max_length=20)),
                ('external_status', models.CharField(blank=True, max_length=50)),
                ('buyer_login', models.CharField(blank=True, max_length=100)),
                ('buyer_full_name', models.CharField(blank=True, max_length=200)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('buyer_phone', models.CharField(blank=True, max_length=30)),
                ('buyer_address', models.CharField(blank=True, max_length=300)),
                ('buyer_city', models.CharField(blank=True, max_length=100)),
                ('buyer_postal_code', models.CharField(blank=True, max_length=20)),
                ('buyer_country', models.CharField(blank=True, max_length=50)),
                ('delivery_recipient_name', models.CharField(blank=True, max_length=200)),
                ('delivery_street', models.CharField(blank=True, max_length=300)),
                ('delivery_city', models.CharField(blank=True, max_length=100)),
                ('delivery_postal_code', models.CharField(blank=True, max_length=20)),
                ('delivery_country_code', models.CharField(blank=True, max_length=10)),
                ('delivery_phone', models.CharField(blank=True, max_length=30)),
                ('delivery_company_name', models.CharField(blank=True, max_length=200)),
                ('delivery_method_name', models.CharField(blank=True, max_length=100)),
                ('delivery_pickup_point_id', models.CharField(blank=True, max_length=100)),
                ('delivery_pickup_point_name', models.CharField(blank=True, max_length=200)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('total_to_pay', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_cogs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_packaging_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('message_to_seller', models.TextField(blank=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='marketplaces.marketplace')),
            ],
            options={
                'verbose_name': 'Zamówienie',
                'verbose_name_plural': 'Zamówienia',
                'ordering': ['-placed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_offer_id', models.CharField(max_length=50)),
                ('external_offer_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Pozycja zamówienia',
                'verbose_name_plural': 'Pozycje zamówienia',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['marketplace', 'status'], name='orders_marketplace_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-placed_at'], name='orders_placed_at_idx'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['external_offer_id'], name='orders_line_offer_idx'),
        ),
    ]
