# Generated by Django 6.1 on 2026-09-04 16:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost_source',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Wpisany ręcznie'), ('ALLEGRO', 'Pobrany z Allegro')], max_length=10),
        ),
    ]
