# Generated by Django 6.1 on 2026-09-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_shipping_cost_order_shipping_cost_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_packaging_cost',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='currency',
        ),
        migrations.AlterField(
            model_name='orderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
