# Generated by Django 6.1 on 2026-09-01 13:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_item_type'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_received', models.PositiveIntegerField()),
                ('quantity_remaining', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_at', models.DateField(default=django.utils.timezone.localdate)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('document_reference', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Przyjęcie magazynowe',
                'verbose_name_plural': 'Przyjęcia magazynowe',
                'ordering': ['received_at', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='stocklevel',
            name='inventory_stocklevel_product_location_unique',
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_batches', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_batches', to='catalog.product'),
        ),
        migrations.RemoveField(
            model_name='stocklevel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='stocklevel',
            name='product',
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['product', 'location'], name='inventory_batch_prod_loc_idx'),
        ),
        migrations.DeleteModel(
            name='StockLevel',
        ),
    ]
