# Generated by Django 6.1 on 2026-09-01 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('item_type', models.CharField(choices=[('MERCHANDISE', 'Merchandise'), ('CONSUMABLE', 'Consumable')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('species', models.CharField(blank=True, max_length=200)),
                ('latin_name', models.CharField(blank=True, max_length=200)),
                ('genus', models.CharField(blank=True, max_length=200)),
                ('variety', models.CharField(blank=True, max_length=200)),
                ('pot_size', models.CharField(blank=True, max_length=200)),
                ('low_stock_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dimension_unit', models.CharField(blank=True, choices=[('CM', 'Centimeters'), ('M', 'Meters')], max_length=2)),
                ('material_unit', models.CharField(blank=True, choices=[('PIECES', 'Pieces'), ('METERS', 'Meters')], max_length=10)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('sku',), name='catalog_product_sku_unique')],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='catalog/products/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, editable=False, upload_to='catalog/products/thumbnails/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
