# Generated by Django 6.1 on 2026-09-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dimension_unit',
            field=models.CharField(blank=True, choices=[('CM', 'Centymetry (cm)'), ('M', 'Metry (m)')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('MERCHANDISE', 'Towar (roślina)'), ('CONSUMABLE', 'Materiał eksploatacyjny')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='material_unit',
            field=models.CharField(blank=True, choices=[('PIECES', 'Sztuka (szt.)'), ('METERS', 'Metr (m)')], max_length=10),
        ),
    ]
