# Generated by Django 6.1 on 2026-09-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_options_alter_productimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('MERCHANDISE', 'Towar (roślina)'), ('CONSUMABLE', 'Materiał eksploatacyjny')], default='MERCHANDISE', max_length=20),
        ),
    ]
